# This workflow will build a golang project and release
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Junca Build And Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  discussions: write

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          cache: true

      - name: Build
        run: |
          GOOS=linux
          GOARCH=amd64
          make
          echo ${{ github.ref }}
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          tar -cvf junca_${{ github.ref_name }}_Linux_amd64.tar.gz ./build/bin/junca

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: New Release ${{ github.ref_name }}.
          draft: false
          prerelease: false
          files: junca_${{ github.ref_name }}_Linux_amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}